openapi: 3.0.3
info:
  title: Web IDE
  description: Web IDE
  version: 1.0.1
servers:
  - url: 'http://localhost:8080/api'
paths:
  /v1/auth/email:
    $ref: './auth/email.yaml'
  /v1/auth/email/check:
    $ref: './auth/emailCheck.yaml'
  /v1/auth/signin:
    $ref: './auth/signin.yaml'
  /v1/auth/signup:
    $ref: './auth/signup.yaml'
  /v1/auth/password/reset/email:
    $ref: './auth/passwordReset.yaml'
  /v1/auth/password/reset/check:
    $ref: './auth/passwordResetCheck.yaml'
  /v1/projects:
    $ref: './project/create.yaml'
  /v1/projects/{id}:
    $ref: './project/update.yaml'
#  /v1/projects/{id}/run:
#    $ref: './project/run.yaml'
  /v1/projects/{id}/invite:
    $ref: './project/invite.yaml'
  /v1/projects/{id}/files:
    $ref: './file/file.yaml'
  /v1/projects/{projectId}/files/{fileId}:
    $ref: './project/save.yaml'
  /v1/projects/{projectId}/files/{fileId}/run:
    $ref: './file/run.yaml'
