openapi: 3.0.3
info:
  title: Web IDE
  description: Web IDE
  version: 1.0.1
servers:
  - url: 'http://localhost:8080/api'
paths:
  /v1/auth/email:
    post:
      summary: 이메일 인증
      description: 입력한 이메일로 인증번호 요청
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 이메일
      responses:
        '200':
          description: 인증번호 전송 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: 인증번호 전송 성공 메시지
        '401':
          description: 인증번호 전송 실패
  /v1/auth/email/check:
    post:
      summary: 이메일 인증 번호 체크
      description: 이메일 인증을 위한 인증번호 체크
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 이메일
                authNumber:
                  type: string
                  description: 인증번호
      responses:
        '200':
          description: 인증 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    description: 인증 유무 코드
                  message:
                    type: string
                    description: 인증 유무 메시지
        '401':
          description: 인증 실패
  /v1/auth/signin:
    post:
      summary: 로그인
      description: 이메일과 비밀번호로 로그인
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 이메일
                password:
                  type: string
                  description: 비밀번호
      responses:
        '200':
          description: 로그인 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    description: 인증 토큰
        '401':
          description: 로그인 실패
  /v1/auth/signup:
    post:
      summary: 회원가입
      description: '이메일, 비밀번호로 회원가입'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 이메일
                password:
                  type: string
                  description: 비밀번호
                name:
                  type: String
                  description: 이름
      responses:
        '200':
          description: 회원가입 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    description: 인증 토큰
        '401':
          description: 회원가입 실패
  /v1/projects:
    post:
      summary: 프로젝트 생성
      description: 프로젝트 생성
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
          description: 자격 증명
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 이름
                description:
                  type: string
                  description: 설명
                template:
                  type: string
                  description: 실행 환경 템플릿
      responses:
        '200':
          description: 프로젝트 생성 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                    description: 프로젝트 식별자
                  storageId:
                    type: string
                    description: 스토리지 내 프로젝트 식별자
    get:
      summary: 프로젝트 목록 보기
      description: 사용자가 소유하거나 수정할 수 있는 프로젝트 목록 보기
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
          description: 자격 증명
      responses:
        '200':
          description: 프로젝트 목록
          content:
            application/json:
              schema:
                type: array
                items:
                  description: 프로젝트 목록
                  type: object
                  properties:
                    id:
                      type: number
                      description: 프로젝트 식별자
                    storage_id:
                      type: string
                      description: 스토리지 내 프로젝트 식별자
                    name:
                      type: string
                      description: 이름
                    description:
                      type: string
                      description: 설명
                    updatedAt:
                      type: string
                      format: date
                      description: 수정일
                    collaborators:
                      type: array
                      description: 협업자 리스트
                      items:
                        type: object
                        properties:
                          id:
                            type: number
                            description: 회원 식별자
                          name:
                            type: string
                            description: 회원 이름
  '/v1/projects/{id}':
    put:
      summary: 프로젝트 수정
      description: 프로젝트 수정
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
          description: 자격 증명
        - in: path
          name: id
          schema:
            type: number
          required: true
          description: 프로젝트 식별자
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 이름
                description:
                  type: string
                  description: 설명
      responses:
        '200':
          description: 프로젝트 수정 성공
    delete:
      summary: 프로젝트 삭제
      description: 프로젝트 아이디로 삭제
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
          description: 자격 증명
        - in: path
          name: id
          schema:
            type: number
          required: true
          description: 프로젝트 식별자
      responses:
        '200':
          description: 프로젝트 삭제 성공
  '/v1/projects/{id}/invite':
    post:
      summary: 프로젝트에 사용자 초대
      description: 프로젝트에 사용자의 이메일로 수정 권한 부여
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
          description: 자격 증명
        - in: path
          name: id
          schema:
            type: number
          required: true
          description: 프로젝트 식별자
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 사용자 이메일
      responses:
        '200':
          description: 성공
  '/v1/projects/{id}/files':
    post:
      summary: 파일 생성
      description: 프로젝트 내 파일 생성
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
          description: 자격 증명
        - name: projectId
          in: path
          schema:
            type: number
          required: true
          description: 프로젝트 식별자
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 파일명
                ext:
                  type: string
                  description: 확장자명
      responses:
        '200':
          description: 성공
  '/v1/projects/{projectId}/files/{fileId}':
    get:
      summary: 파일 읽기
      description: 프로젝트 내 파일 읽기
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
          description: 자격 증명
        - name: projectId
          in: path
          schema:
            type: number
          required: true
          description: 프로젝트 식별자
        - name: fileId
          in: path
          schema:
            type: number
          required: true
          description: 파일 식별자
      responses:
        '200':
          description: 파일 내용
          content:
            application/json:
              schema:
                type: object
                properties:
                  fileName:
                    type: string
                    description: 파일명
                  ext:
                    type: string
                    description: 확장자명
                  content:
                    type: string
                    description: 코드 내용
    put:
      summary: 파일 수정
      description: 프로젝트 내 파일 수정
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
          description: 자격 증명
        - name: projectId
          in: path
          schema:
            type: number
          required: true
          description: 프로젝트 식별자
        - name: fileId
          in: path
          schema:
            type: number
          required: true
          description: 파일 식별자
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                  description: 코드 내용
      responses:
        '200':
          description: 성공
  '/v1/projects/{projectId}/files/{fileId}/run':
    get:
      summary: 파일 실행
      description: 프로젝트 내 파일 실행
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
          description: 자격 증명
        - in: path
          name: projectId
          schema:
            type: number
          required: true
          description: 프로젝트 식별자
        - in: path
          name: fileId
          schema:
            type: number
          required: true
          description: 파일 식별자
      responses:
        '200':
          description: 프로젝트 실행 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    description: 프로젝트 실행 결과
                  type:
                    type: string
                    description: 프로젝트 실행 성공 실패 여부
